// Code generated by goyacc grammar.y. DO NOT EDIT.

//line grammar.y:2
package parser

import __yyfmt__ "fmt"

//line grammar.y:2

import "github.com/kkty/compiler/ast"

//line grammar.y:7
type yySymType struct {
	yys  int
	val  interface{}
	node ast.Node
}

const BOOL = 57346
const INT = 57347
const FLOAT = 57348
const NOT = 57349
const MINUS = 57350
const PLUS = 57351
const AST = 57352
const SLASH = 57353
const MINUS_DOT = 57354
const PLUS_DOT = 57355
const AST_DOT = 57356
const SLASH_DOT = 57357
const EQUAL = 57358
const LESS_GREATER = 57359
const LESS_EQUAL = 57360
const GREATER_EQUAL = 57361
const LESS = 57362
const GREATER = 57363
const IF = 57364
const THEN = 57365
const ELSE = 57366
const IDENT = 57367
const LET = 57368
const IN = 57369
const REC = 57370
const COMMA = 57371
const ARRAY_CREATE = 57372
const READ_INT = 57373
const READ_FLOAT = 57374
const PRINT_INT = 57375
const PRINT_CHAR = 57376
const INT_TO_FLOAT = 57377
const FLOAT_TO_INT = 57378
const SQRT = 57379
const DOT = 57380
const LESS_MINUS = 57381
const SEMICOLON = 57382
const LPAREN = 57383
const RPAREN = 57384
const EOF = 57385
const prec_let = 57386
const prec_if = 57387
const prec_tuple = 57388
const prec_unary_minus = 57389
const prec_app = 57390

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"BOOL",
	"INT",
	"FLOAT",
	"NOT",
	"MINUS",
	"PLUS",
	"AST",
	"SLASH",
	"MINUS_DOT",
	"PLUS_DOT",
	"AST_DOT",
	"SLASH_DOT",
	"EQUAL",
	"LESS_GREATER",
	"LESS_EQUAL",
	"GREATER_EQUAL",
	"LESS",
	"GREATER",
	"IF",
	"THEN",
	"ELSE",
	"IDENT",
	"LET",
	"IN",
	"REC",
	"COMMA",
	"ARRAY_CREATE",
	"READ_INT",
	"READ_FLOAT",
	"PRINT_INT",
	"PRINT_CHAR",
	"INT_TO_FLOAT",
	"FLOAT_TO_INT",
	"SQRT",
	"DOT",
	"LESS_MINUS",
	"SEMICOLON",
	"LPAREN",
	"RPAREN",
	"EOF",
	"prec_let",
	"prec_if",
	"prec_tuple",
	"prec_unary_minus",
	"prec_app",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 503

var yyAct = [...]int{

	2, 91, 94, 86, 85, 39, 40, 41, 42, 96,
	75, 52, 51, 106, 82, 93, 38, 95, 49, 57,
	104, 103, 92, 59, 60, 61, 62, 63, 64, 65,
	66, 67, 68, 69, 70, 71, 72, 73, 74, 80,
	78, 102, 100, 77, 79, 19, 20, 21, 43, 10,
	83, 44, 46, 19, 20, 21, 4, 5, 24, 25,
	1, 7, 34, 35, 45, 0, 48, 0, 19, 20,
	21, 6, 0, 0, 9, 8, 88, 89, 90, 11,
	12, 13, 18, 14, 15, 16, 17, 0, 0, 48,
	18, 58, 0, 0, 101, 0, 0, 105, 0, 107,
	108, 109, 82, 110, 0, 18, 0, 112, 0, 0,
	0, 0, 0, 0, 115, 116, 23, 22, 24, 25,
	33, 32, 34, 35, 26, 27, 30, 31, 28, 29,
	0, 0, 0, 0, 0, 0, 0, 37, 23, 22,
	24, 25, 33, 32, 34, 35, 0, 0, 36, 0,
	111, 23, 22, 24, 25, 33, 32, 34, 35, 26,
	27, 30, 31, 28, 29, 0, 0, 0, 0, 0,
	0, 0, 37, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 36, 0, 97, 23, 22, 24, 25,
	33, 32, 34, 35, 26, 27, 30, 31, 28, 29,
	0, 0, 0, 0, 0, 0, 0, 37, 0, 3,
	0, 0, 0, 0, 0, 0, 0, 0, 36, 47,
	87, 50, 0, 0, 53, 54, 55, 56, 0, 0,
	0, 19, 20, 21, 4, 5, 0, 0, 0, 7,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 6,
	0, 0, 9, 8, 0, 0, 81, 11, 12, 13,
	84, 14, 15, 16, 17, 0, 0, 0, 18, 23,
	22, 24, 25, 33, 32, 34, 35, 26, 27, 30,
	31, 28, 29, 0, 0, 0, 0, 0, 114, 0,
	37, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 36, 23, 22, 24, 25, 33, 32, 34, 35,
	26, 27, 30, 31, 28, 29, 0, 0, 0, 0,
	0, 113, 0, 37, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 36, 23, 22, 24, 25, 33,
	32, 34, 35, 26, 27, 30, 31, 28, 29, 0,
	0, 0, 0, 0, 99, 0, 37, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 36, 23, 22,
	24, 25, 33, 32, 34, 35, 26, 27, 30, 31,
	28, 29, 0, 0, 98, 0, 0, 0, 0, 37,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	36, 23, 22, 24, 25, 33, 32, 34, 35, 26,
	27, 30, 31, 28, 29, 0, 76, 0, 0, 0,
	0, 0, 37, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 36, 23, 22, 24, 25, 33, 32,
	34, 35, 26, 27, 30, 31, 28, 29, 0, 0,
	0, 0, 0, 0, 0, 37, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 36, 23, 22, 24,
	25, 33, 32, 34, 35, 26, 27, 30, 31, 28,
	29, 0, 0, 0, 0, 0, 0, 0, 37, 23,
	22, 24, 25, 33, 32, 34, 35, 26, 27, 30,
	31, 28, 29,
}
var yyPact = [...]int{

	227, -1000, 426, -22, 227, 227, 227, 227, 23, 41,
	-11, 41, -29, -30, 41, 41, 41, 41, 49, -1000,
	-1000, -1000, 227, 227, 227, 227, 227, 227, 227, 227,
	227, 227, 227, 227, 227, 227, 227, 227, -31, -1000,
	-1000, 393, -1000, 27, 15, 14, 41, -24, -1000, 227,
	64, -38, -39, -24, -24, -24, -24, 178, -1000, 48,
	48, -1000, -1000, 130, 130, 130, 130, 130, 130, 48,
	48, -1000, -1000, 426, 481, 227, 227, 227, -3, -27,
	-12, -24, -32, 481, -24, -1000, -1000, -1000, 143, 360,
	327, 26, -3, 25, -4, -5, 227, -26, 227, 227,
	227, -1000, 227, -1000, -1000, 108, 227, 459, 426, 294,
	261, -1000, 459, 227, 227, 426, 426,
}
var yyPgo = [...]int{

	0, 60, 0, 209, 1, 52, 49, 44,
}
var yyR1 = [...]int{

	0, 1, 3, 3, 3, 3, 3, 3, 3, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 4, 4, 5, 5, 6, 6, 7,
	7,
}
var yyR2 = [...]int{

	0, 1, 3, 2, 1, 1, 1, 1, 5, 1,
	2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 6, 2, 3, 3, 3, 3, 6, 8,
	2, 1, 8, 7, 3, 2, 3, 3, 3, 2,
	2, 2, 2, 2, 1, 2, 1, 3, 3, 3,
	3,
}
var yyChk = [...]int{

	-1000, -1, -2, -3, 7, 8, 22, 12, 26, 25,
	-6, 30, 31, 32, 34, 35, 36, 37, 41, 4,
	5, 6, 9, 8, 10, 11, 16, 17, 20, 21,
	18, 19, 13, 12, 14, 15, 40, 29, 38, -2,
	-2, -2, -2, 25, 28, 41, -5, -3, 25, 29,
	-3, 41, 41, -3, -3, -3, -3, -2, 42, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, 41, 23, 16, 25, -7,
	25, -3, 38, -2, -3, 42, 42, 42, -2, -2,
	-2, -4, 25, 42, 29, 29, 41, 42, 24, 27,
	16, -4, 16, 25, 25, -2, 39, -2, -2, -2,
	-2, 42, -2, 27, 27, -2, -2,
}
var yyDef = [...]int{

	0, -2, 1, 9, 0, 0, 0, 0, 0, 7,
	31, 0, 0, 0, 0, 0, 0, 0, 0, 4,
	5, 6, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 35, 0, 0, 10,
	11, 0, 23, 0, 0, 0, 30, 46, 7, 0,
	0, 0, 0, 39, 40, 41, 42, 0, 3, 12,
	13, 14, 15, 16, 17, 18, 19, 20, 21, 24,
	25, 26, 27, 34, 48, 0, 0, 0, 0, 0,
	0, 45, 0, 47, 36, 37, 38, 2, 0, 0,
	0, 0, 44, 0, 0, 0, 0, 8, 0, 0,
	0, 43, 0, 49, 50, 0, 0, 22, 28, 0,
	0, 8, 33, 0, 0, 29, 32,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:80
		{
			yylex.(*lexer).result = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:83
		{
			yyVAL.node = yyDollar[2].node
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:85
		{
			yyVAL.node = &ast.Unit{}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:87
		{
			yyVAL.node = &ast.Bool{yyDollar[1].val.(bool)}
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:89
		{
			yyVAL.node = &ast.Int{yyDollar[1].val.(int32)}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:91
		{
			yyVAL.node = &ast.Float{yyDollar[1].val.(float32)}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:93
		{
			yyVAL.node = &ast.Variable{yyDollar[1].val.(string)}
		}
	case 8:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:95
		{
			yyVAL.node = &ast.ArrayGet{yyDollar[1].node, yyDollar[4].node}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:98
		{
			yyVAL.node = yyDollar[1].node
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:101
		{
			yyVAL.node = &ast.Not{yyDollar[2].node}
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:104
		{
			yyVAL.node = &ast.Neg{yyDollar[2].node}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:106
		{
			yyVAL.node = &ast.Add{yyDollar[1].node, yyDollar[3].node}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:108
		{
			yyVAL.node = &ast.Sub{yyDollar[1].node, yyDollar[3].node}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:111
		{
			yyVAL.node = &ast.FloatToInt{&ast.FloatMul{&ast.IntToFloat{yyDollar[1].node}, &ast.IntToFloat{yyDollar[3].node}}}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:113
		{
			yyVAL.node = &ast.FloatToInt{&ast.FloatSub{&ast.FloatDiv{&ast.IntToFloat{yyDollar[1].node}, &ast.IntToFloat{yyDollar[3].node}}, &ast.Float{0.4999}}}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:115
		{
			yyVAL.node = &ast.Equal{yyDollar[1].node, yyDollar[3].node}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:117
		{
			yyVAL.node = &ast.Not{&ast.Equal{yyDollar[1].node, yyDollar[3].node}}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:119
		{
			yyVAL.node = &ast.LessThan{yyDollar[1].node, yyDollar[3].node}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:121
		{
			yyVAL.node = &ast.LessThan{yyDollar[3].node, yyDollar[1].node}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:123
		{
			yyVAL.node = &ast.Not{&ast.LessThan{yyDollar[3].node, yyDollar[1].node}}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:125
		{
			yyVAL.node = &ast.Not{&ast.LessThan{yyDollar[1].node, yyDollar[3].node}}
		}
	case 22:
		yyDollar = yyS[yypt-6 : yypt+1]
//line grammar.y:128
		{
			yyVAL.node = &ast.If{yyDollar[2].node, yyDollar[4].node, yyDollar[6].node}
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:131
		{
			yyVAL.node = &ast.FloatNeg{yyDollar[2].node}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:133
		{
			yyVAL.node = &ast.FloatAdd{yyDollar[1].node, yyDollar[3].node}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:135
		{
			yyVAL.node = &ast.FloatSub{yyDollar[1].node, yyDollar[3].node}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:137
		{
			yyVAL.node = &ast.FloatMul{yyDollar[1].node, yyDollar[3].node}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:139
		{
			yyVAL.node = &ast.FloatDiv{yyDollar[1].node, yyDollar[3].node}
		}
	case 28:
		yyDollar = yyS[yypt-6 : yypt+1]
//line grammar.y:142
		{
			yyVAL.node = &ast.Assignment{yyDollar[2].val.(string), yyDollar[4].node, yyDollar[6].node}
		}
	case 29:
		yyDollar = yyS[yypt-8 : yypt+1]
//line grammar.y:145
		{
			yyVAL.node = &ast.FunctionAssignment{yyDollar[3].val.(string), yyDollar[4].val.([]string), yyDollar[6].node, yyDollar[8].node}
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:148
		{
			yyVAL.node = &ast.Application{yyDollar[1].val.(string), yyDollar[2].val.([]ast.Node)}
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:151
		{
			yyVAL.node = &ast.Tuple{yyDollar[1].val.([]ast.Node)}
		}
	case 32:
		yyDollar = yyS[yypt-8 : yypt+1]
//line grammar.y:153
		{
			yyVAL.node = &ast.TupleAssignment{yyDollar[3].val.([]string), yyDollar[6].node, yyDollar[8].node}
		}
	case 33:
		yyDollar = yyS[yypt-7 : yypt+1]
//line grammar.y:155
		{
			yyVAL.node = &ast.ArrayPut{yyDollar[1].node, yyDollar[4].node, yyDollar[7].node}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:157
		{
			yyVAL.node = &ast.Assignment{"", yyDollar[1].node, yyDollar[3].node}
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:159
		{
			yyVAL.node = yyDollar[1].node
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:162
		{
			yyVAL.node = &ast.ArrayCreate{yyDollar[2].node, yyDollar[3].node}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:165
		{
			yyVAL.node = &ast.ReadInt{}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:168
		{
			yyVAL.node = &ast.ReadFloat{}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:171
		{
			yyVAL.node = &ast.WriteByte{yyDollar[2].node}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:174
		{
			yyVAL.node = &ast.IntToFloat{yyDollar[2].node}
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:177
		{
			yyVAL.node = &ast.FloatToInt{yyDollar[2].node}
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:180
		{
			yyVAL.node = &ast.Sqrt{yyDollar[2].node}
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:183
		{
			yyVAL.val = append([]string{yyDollar[1].val.(string)}, yyDollar[2].val.([]string)...)
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:185
		{
			yyVAL.val = []string{yyDollar[1].val.(string)}
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:189
		{
			yyVAL.val = append(yyDollar[1].val.([]ast.Node), yyDollar[2].node)
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:192
		{
			yyVAL.val = []ast.Node{yyDollar[1].node}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:195
		{
			yyVAL.val = append(yyDollar[1].val.([]ast.Node), yyDollar[3].node)
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:197
		{
			yyVAL.val = append([]ast.Node{yyDollar[1].node}, yyDollar[3].node)
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:200
		{
			yyVAL.val = append(yyDollar[1].val.([]string), yyDollar[3].val.(string))
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:202
		{
			yyVAL.val = append([]string{yyDollar[1].val.(string)}, yyDollar[3].val.(string))
		}
	}
	goto yystack /* stack new state and value */
}
