on: [push]
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - uses: actions/checkout@v1
    - run: go test ./test -coverpkg ./...
